# 打字机效果配置
typing_settings:
  # 每个字符的延迟时间（秒）
  char_delay: 0.1
  # 每段最大的延迟时间（秒）
  segment_delay_max: 10
  # 每段之间的额外停顿时间（秒）
  segment_pause: 0.5
  # 最大分段长度，超过此长度将不进行分段
  max_split_length: 75
  # 分段模式，default 使用复杂规则细分，simple只依赖换行符
  split_mode: "default"
