# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
import sys
from pathlib import Path

from langbot_plugin.api.definition.plugin import BasePlugin


class SplitTypingRev(BasePlugin):
    async def initialize(self) -> None:
        await super().initialize()

        # Import local modules
        plugin_path = Path(__file__).parent
        if str(plugin_path) not in sys.path:
            sys.path.insert(0, str(plugin_path))

        logging.info(f"🧩SplitTyping Plugin initialized successfully")

        from pkg.config import init_config
        from pkg.state import init_state

        config = self.get_config()
        # Initialize global config and state
        init_config(
            split_mode=config.get("split_mode", "default"),
            char_delay=config.get("char_delay", 0.1),
            segment_delay_max=config.get("segment_delay_max", 2.0),
            segment_pause=config.get("segment_pause", 0.5),
            max_segment_length=config.get("max_segment_length", 50),
        )
        init_state()

    def __del__(self) -> None:
        pass
