apiVersion: v1
kind: Plugin
metadata:
  author: Sansui233
  name: SplitTyping-Rev
  repository: ''
  version: 0.1.0
  description:
    en_US: Split the message into short sentences to simulate typing time
    zh_Hans: 消息拆分为短句，模拟打字时间
  label:
    en_US: SplitTyping Rev
    zh_Hans: 拆句打字
  icon: assets/icon.svg
spec:
  config: 
    - name: split_mode
      type: select
      options:
        - name: simple
          label:
            en_US: Simple
            zh_Hans: 简单
        - name: default
          label:
            en_US: Default
            zh_Hans: 普通
      description:
        en_US: Mode of splitting text
        zh_Hans: 分段模式
    - name: char_delay
      type: float
      default: 0.1
      description:
        en_US: Delay per character in seconds
        zh_Hans: 每个字符的延迟时间（秒）
    - name: segment_delay_max
      type: float
      default: 2.0
      description:
        en_US: Maximum delay between segments in seconds
        zh_Hans: 分段之间的最大延迟时间（秒）
    - name: segment_pause
      type: float
      default: 0.5
      description:
        en_US: Pause duration between segments in seconds
        zh_Hans: 分段之间的暂停时间（秒）
    - name: max_segment_length
      type: int
      default: 50
      description:
        en_US: Maximum length of each segment
        zh_Hans: 每个分段的最大长度
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
    Command:
      fromDirs:
      - path: components/commands/
execution:
  python:
    path: main.py
    attr: SplitTypingRev
