# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from typing import AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import (
    CommandReturn,
    ExecuteContext,
)

from lib.state import get_state


class SplitText(Command):
    async def initialize(self) -> None:
        await super().initialize()

        @self.subcommand(name="on", help="开启分段", usage="!split_text on", aliases=[])
        async def send(
            self, ctx: ExecuteContext
        ) -> AsyncGenerator[CommandReturn, None]:
            chat_type = ctx.event.launcher_type  # type: ignore
            chat_id = (
                ctx.event.launcher_id if chat_type == "group" else ctx.event.sender_id  # type: ignore
            )

            get_state().enable(chat_id)
            yield CommandReturn(text=f"已开启分段发送。")

        # 关闭分段
        @self.subcommand(
            name="off", help="关闭分段", usage="!split_text off", aliases=[]
        )
        async def send(
            self, ctx: ExecuteContext
        ) -> AsyncGenerator[CommandReturn, None]:
            chat_type = ctx.event.launcher_type  # type: ignore
            chat_id = (
                ctx.event.launcher_id if chat_type == "group" else ctx.event.sender_id  # type: ignore
            )

            get_state().disable(chat_id)
            yield CommandReturn(text=f"已关闭分段发送。")
