# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
from typing import AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import (
    CommandReturn,
    ExecuteContext,
)


class SplitText(Command):
    async def initialize(self) -> None:
        await super().initialize()

        from pkg.state import get_state, uid

        logger = logging.getLogger("split_typing_plugin")

        @self.subcommand(name="on", help="开启分段", usage="!split_text on", aliases=[])
        async def sendon(
            self, ctx: ExecuteContext
        ) -> AsyncGenerator[CommandReturn, None]:
            chat_type = ctx.session.launcher_type
            chat_id = (
                ctx.session.launcher_id
                if chat_type == "group"
                else ctx.session.sender_id
            )
            if chat_id is None:
                logger.error(f"🧩SplitTyping {chat_id} 为空")
                return

            get_state().enable(uid(chat_type.value, chat_id))
            logger.info(f"🧩SplitTyping {chat_id} 已开启分段发送。")
            yield CommandReturn(text=f"已开启分段发送。")

        # 关闭分段
        @self.subcommand(
            name="off", help="关闭分段", usage="!split_text off", aliases=[]
        )
        async def sendoff(
            self, ctx: ExecuteContext
        ) -> AsyncGenerator[CommandReturn, None]:
            logger.debug(
                f"🧩SplitTyping {ctx.session.launcher_type.value}_{ctx.session.launcher_id}_{ctx.session.sender_id}"
            )
            chat_type = ctx.session.launcher_type
            chat_id = (
                ctx.session.launcher_id
                if chat_type == "group"
                else ctx.session.sender_id
            )

            if chat_id is None:
                logger.error(f"🧩SplitTyping {chat_id} 为空")
                return

            get_state().disable(uid(chat_type.value, chat_id))
            logger.info(f"🧩SplitTyping {chat_id} 已关闭分段发送。")
            yield CommandReturn(text=f"已关闭分段发送。")
